[build]
  command = "npm run build"
  publish = "dist"
  base = "present-ponder"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  # Disable Python detection
  PYTHON_VERSION = ""
  # Force Node.js environment
  NIXPACKS_NO_DEFAULT_CACHE = "true"

# Environment variables (set these in Netlify dashboard)
# VITE_API_BASE_URL = "https://your-backend-url.railway.app"
# VITE_SUPABASE_URL = "your_supabase_url"
# VITE_SUPABASE_PUBLISHABLE_KEY = "your_supabase_key"
