[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Netlify dashboard)
# VITE_API_BASE_URL = "https://your-backend-url.railway.app"
# VITE_SUPABASE_URL = "your_supabase_url"
# VITE_SUPABASE_PUBLISHABLE_KEY = "your_supabase_key"
